GERMAN_TO_ENGLISH_COUNTRY = {
    "Afghanistan": "Afghanistan",
    "Ägypten": "Egypt",
    "Albanien": "Albania",
    "Algerien": "Algeria",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua und Barbuda": "Antigua and Barbuda",
    "Argentinien": "Argentina",
    "Armenien": "Armenia",
    "Aserbaidschan": "Azerbaijan",
    "Australien": "Australia",
    "Österreich": "Austria",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahrain",
    "Bangladesch": "Bangladesh",
    "Barbados": "Barbados",
    "Belgien": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivien": "Bolivia",
    "Bosnien und Herzegowina": "Bosnia and Herzegovina",
    "Botsuana": "Botswana",
    "Brasilien": "Brazil",
    "Brunei": "Brunei",
    "Bulgarien": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Chile": "Chile",
    "China": "China",
    "Costa Rica": "Costa Rica",
    "Dänemark": "Denmark",
    "Deutschland": "Germany",
    "Dominica": "Dominica",
    "Dominikanische Republik": "Dominican Republic",
    "Ecuador": "Ecuador",
    "El Salvador": "El Salvador",
    "Eritrea": "Eritrea",
    "Estland": "Estonia",
    "Fidschi": "Fiji",
    "Finnland": "Finland",
    "Frankreich": "France",
    "Gabun": "Gabon",
    "Gambia": "Gambia",
    "Georgien": "Georgia",
    "Ghana": "Ghana",
    "Grenada": "Grenada",
    "Griechenland": "Greece",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Indien": "India",
    "Indonesien": "Indonesia",
    "Irak": "Iraq",
    "Iran": "Iran",
    "Irland": "Ireland",
    "Island": "Iceland",
    "Israel": "Israel",
    "Italien": "Italy",
    "Jamaika": "Jamaica",
    "Japan": "Japan",
    "Jemen": "Yemen",
    "Jordanien": "Jordan",
    "Kambodscha": "Cambodia",
    "Kamerun": "Cameroon",
    "Kanada": "Canada",
    "Kap Verde": "Cabo Verde",
    "Kasachstan": "Kazakhstan",
    "Katar": "Qatar",
    "Kenia": "Kenya",
    "Kirgisistan": "Kyrgyzstan",
    "Kiribati": "Kiribati",
    "Kolumbien": "Colombia",
    "Komoren": "Comoros",
    "Kongo": "Congo",
    "Kroatien": "Croatia",
    "Kuba": "Cuba",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Lesotho": "Lesotho",
    "Lettland": "Latvia",
    "Libanon": "Lebanon",
    "Liberia": "Liberia",
    "Libyen": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Litauen": "Lithuania",
    "Luxemburg": "Luxembourg",
    "Madagaskar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Malediven": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marokko": "Morocco",
    "Marshallinseln": "Marshall Islands",
    "Mauretanien": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexiko": "Mexico",
    "Mikronesien": "Micronesia",
    "Monaco": "Monaco",
    "Mongolei": "Mongolia",
    "Montenegro": "Montenegro",
    "Mosambik": "Mozambique",
    "Myanmar": "Myanmar",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Neuseeland": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Nordkorea": "North Korea",
    "Norwegen": "Norway",
    "Oman": "Oman",
    "Östtimor": "Timor-Leste",
    "Pakistan": "Pakistan",
    "Palau": "Palau",
    "Panama": "Panama",
    "Papua‑Neuguinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippinen": "Philippines",
    "Polen": "Poland",
    "Portugal": "Portugal",
    "Ruanda": "Rwanda",
    "Rumänien": "Romania",
    "Russland": "Russia",
    "Salomonen": "Solomon Islands",
    "Sambia": "Zambia",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "São Tomé und Príncipe": "Sao Tome and Principe",
    "Saudi‑Arabien": "Saudi Arabia",
    "Schweden": "Sweden",
    "Schweiz": "Switzerland",
    "Senegal": "Senegal",
    "Serbien": "Serbia",
    "Seychellen": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapur": "Singapore",
    "Slowakei": "Slovakia",
    "Slowenien": "Slovenia",
    "Somalia": "Somalia",
    "Spanien": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Südafrika": "South Africa",
    "Südkorea": "South Korea",
    "Südsudan": "South Sudan",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Tadschikistan": "Tajikistan",
    "Tansania": "Tanzania",
    "Thailand": "Thailand",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad und Tobago": "Trinidad and Tobago",
    "Tschad": "Chad",
    "Tschechien": "Czechia",
    "Tunesien": "Tunisia",
    "Türkei": "Turkey",
    "Turkmenistan": "Turkmenistan",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "Ungarn": "Hungary",
    "Uruguay": "Uruguay",
    "Usbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vatikanstadt": "Holy See",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Zentralafrikanische Republik": "Central African Republic",
    "Zypern": "Cyprus"
}
